//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSoftware
{
    using BankSoftware.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankEntities : DbContext
    {
        public BankEntities()
            : base("name=BankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

 
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
       // public virtual DbSet<TransactionModel> TransactionHistory { get; set; }
        public System.Data.Entity.DbSet<BankSoftware.Models.UserAccountModel> UserAccountModels { get; set; }

        public System.Data.Entity.DbSet<BankSoftware.Models.ProfileModel> ProfileModels { get; set; }

 
        public object UserAccountModel { get; internal set; }
    }
}
