//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSoftware
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int UA_ID { get; set; }
        public string UA_NO { get; set; }
        public string UA_Holder { get; set; }
        public string Balance { get; set; }
        public string UtilityBillType { get; internal set; }
        public decimal UtilityBillAmount { get; internal set; }
    }
}
